import React, { useState } from 'react';
import { createPortal } from 'react-dom';
import '../styles/ScoreMethodologyInfo.css';

const RUBRIC = [
  { score: 5, label: 'Excellent', desc: 'Consistently praised' },
  { score: 4, label: 'Good', desc: 'Mostly praised' },
  { score: 3, label: 'Average', desc: 'Mixed reviews' },
  { score: 2, label: 'Below average', desc: 'Mixed, more negatives' },
  { score: 1, label: 'Poor', desc: 'Consistently criticized' },
];

export default function ScoreMethodologyInfo({ label = 'How are these calculated?' }) {
  const [open, setOpen] = useState(false);

  return (
    <>
      <button
        type="button"
        className="methodology-trigger"
        onClick={(e) => {
          e.stopPropagation();
          setOpen(true);
        }}
        aria-label="How quality scores are calculated"
      >
        <span className="methodology-trigger-icon" aria-hidden="true">
          i
        </span>
        {label && <span className="methodology-trigger-label">{label}</span>}
      </button>

      {open &&
        createPortal(
          <div className="methodology-scrim" onClick={() => setOpen(false)}>
            <div
              className="methodology-modal"
              role="dialog"
              aria-modal="true"
              aria-label="How quality scores are calculated"
              onClick={(e) => e.stopPropagation()}
            >
              <button className="methodology-close" onClick={() => setOpen(false)} aria-label="Close">
                &times;
              </button>
              <h2>How Quality Scores Are Calculated</h2>

              <p>
                Each book&apos;s six quality dimensions — Prose, Romance, World-Building, Pacing,
                Emotional Payoff, and Character Depth — are generated by an AI model that reads
                real reader reviews gathered from Reddit (r/Romantasy, r/RomanceBooks, r/Fantasy)
                and Google Books, then scores each dimension and writes a short synthesis.
              </p>

              <h3>Scoring rubric</h3>
              <table className="methodology-rubric">
                <tbody>
                  {RUBRIC.map((r) => (
                    <tr key={r.score}>
                      <td className="rubric-score">{r.score}</td>
                      <td className="rubric-label">{r.label}</td>
                      <td className="rubric-desc">{r.desc}</td>
                    </tr>
                  ))}
                </tbody>
              </table>

              <h3>Confidence labels</h3>
              <ul>
                <li>
                  <strong>High</strong> — many corroborating reviews for that dimension.
                </li>
                <li>
                  <strong>Medium</strong> — a moderate or mixed sample of reviews.
                </li>
                <li>
                  <strong>Low</strong> — fewer than 5 reviews were found for that dimension. Treat
                  the score as a rough signal, not a verdict.
                </li>
              </ul>

              <h3>Overall score</h3>
              <p>
                The star rating shown on each book&apos;s card is a simple average of its six
                dimension scores — a different number from the Google Books star rating, which
                appears separately in the book&apos;s description.
              </p>

              <p className="methodology-disclaimer">
                These are AI-generated syntheses of aggregate reader sentiment, not human
                editorial scores. They can miss nuance or be wrong — treat them as a starting
                signal, not a guarantee.
              </p>
            </div>
          </div>,
          document.body
        )}
    </>
  );
}
