import React, { useState } from 'react';
import { createPortal } from 'react-dom';
import '../styles/ScoreMethodologyInfo.css';

const RUBRIC = [
  { score: 5, label: 'Excellent', desc: 'Consistently praised' },
  { score: 4, label: 'Good', desc: 'Mostly praised' },
  { score: 3, label: 'Average', desc: 'Mixed reviews' },
  { score: 2, label: 'Below average', desc: 'Mixed, more negatives' },
  { score: 1, label: 'Poor', desc: 'Consistently criticized' },
];

const CRAFT_FLAG_GROUPS = [
  {
    title: 'Writing style',
    values: 'Accessible, Literary, Lyrical, Sparse, Purple / ornate, or Conversational',
    note: 'A descriptive label for how the prose reads — not itself a quality judgment. A "Purple / ornate" style isn’t worse than "Accessible," just different.',
  },
  {
    title: 'Grammar',
    values: 'Clean, Minor issues, or Notable issues',
    note: 'Only set when reviewers specifically called out typos, editing, or technical writing problems.',
  },
  {
    title: 'Dialogue',
    values: 'Natural, Mixed, or Stilted',
    note: 'Only set when reviewers specifically commented on how the dialogue reads.',
  },
];

// 'full' is the whole methodology (per-dimension rubric, confidence labels,
// craft-flag badges) — used wherever those individual dimensions are shown.
// 'overall' is scoped down to just the Overall-score explanation, for
// contexts (like the Quick Search quality dropdown) that only ever expose
// the single aggregate number and have no per-dimension breakdown on screen
// to explain the rest of the modal against.
export default function ScoreMethodologyInfo({ label = 'How are these calculated?', scope = 'full' }) {
  const [open, setOpen] = useState(false);
  const isOverallOnly = scope === 'overall';

  return (
    <>
      <button
        type="button"
        className="methodology-trigger"
        onClick={(e) => {
          e.stopPropagation();
          setOpen(true);
        }}
        aria-label={isOverallOnly ? 'How the Overall quality score works' : 'How quality scores are calculated'}
      >
        <span className="methodology-trigger-icon" aria-hidden="true">
          i
        </span>
        {label && <span className="methodology-trigger-label">{label}</span>}
      </button>

      {open &&
        createPortal(
          <div className="methodology-scrim" onClick={() => setOpen(false)}>
            <div
              className="methodology-modal"
              role="dialog"
              aria-modal="true"
              aria-label={isOverallOnly ? 'How the Overall quality score works' : 'How quality scores are calculated'}
              onClick={(e) => e.stopPropagation()}
            >
              <button className="methodology-close" onClick={() => setOpen(false)} aria-label="Close">
                &times;
              </button>

              {isOverallOnly ? (
                <>
                  <h2>How the Overall Quality Score Works</h2>
                  <p>
                    Overall is a simple average of a book&apos;s six quality dimensions — Prose,
                    Romance, World-Building, Pacing, Emotional Payoff, and Character Depth — each
                    distilled by an AI model from real reader reviews. It&apos;s a different
                    number from the filled-star real reader rating (Hardcover or Google Books),
                    which appears separately.
                  </p>
                  <p>
                    This makes it a deliberately stricter bar than a single star rating. A book
                    everyone loves can still average a 3-point-something overall if reviewers
                    consistently flag one or two weak spots (clunky prose, thin side characters)
                    alongside real strengths — that&apos;s the score correctly reflecting a mixed
                    craft profile, not an error. Clearing 4.5+ means a book scored strong across
                    all six dimensions at once, not just that people enjoyed reading it, so very
                    few books reach that bar even among widely-loved bestsellers.
                  </p>
                  <p className="methodology-disclaimer">
                    This is an AI-generated distillation of aggregate reader sentiment, not a human
                    editorial score. It can miss nuance or be wrong — treat it as a starting
                    signal, not a guarantee.
                  </p>
                </>
              ) : (
                <>
                  <h2>How Quality Scores Are Calculated</h2>

                  <p>
                    Each book&apos;s six quality dimensions — Prose, Romance, World-Building, Pacing,
                    Emotional Payoff, and Character Depth — are generated by an AI model that reads
                    real reader reviews (from Hardcover and review blogs), weighs them against the
                    book&apos;s aggregate rating, then scores each dimension and writes a short
                    distillation.
                  </p>

                  <h3>Scoring rubric</h3>
                  <table className="methodology-rubric">
                    <tbody>
                      {RUBRIC.map((r) => (
                        <tr key={r.score}>
                          <td className="rubric-score">{r.score}</td>
                          <td className="rubric-label">{r.label}</td>
                          <td className="rubric-desc">{r.desc}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>

                  <h3>Confidence labels</h3>
                  <ul>
                    <li>
                      <strong>High</strong> — many corroborating reviews for that dimension.
                    </li>
                    <li>
                      <strong>Medium</strong> — a moderate or mixed sample of reviews.
                    </li>
                    <li>
                      <strong>Low</strong> — fewer than 5 reviews were found for that dimension. Treat
                      the score as a rough signal, not a verdict.
                    </li>
                  </ul>

                  <h3>Style, grammar &amp; dialogue badges</h3>
                  <p>
                    Small badges sometimes appear under a book&apos;s Prose Quality section, flagging
                    specific things reviewers mentioned:
                  </p>
                  <ul className="methodology-craft-flags">
                    {CRAFT_FLAG_GROUPS.map((g) => (
                      <li key={g.title}>
                        <strong>{g.title}</strong> — {g.values}
                        <br />
                        <span className="methodology-craft-flag-note">{g.note}</span>
                      </li>
                    ))}
                  </ul>
                  <p>
                    These badges are conditional, not exhaustive — a book only gets one when reviewers
                    actually raised that specific point. A missing badge doesn&apos;t mean the grammar
                    was checked and found clean, or the dialogue was checked and found fine; it means
                    no reviews commented on it either way. Some books will have all three, some none,
                    depending on what reviewers happened to talk about.
                  </p>

                  <h3>Overall score</h3>
                  <p>
                    The outline-star rating shown on each book&apos;s card is a simple average of its
                    six dimension scores — a different number from the filled-star real reader rating
                    (Hardcover or Google Books), which appears separately.
                  </p>
                  <p>
                    This makes it a deliberately stricter bar than a single star rating. A book everyone
                    loves can still average a 3-point-something overall if reviewers consistently flag
                    one or two weak spots (clunky prose, thin side characters) alongside real strengths —
                    that&apos;s the score correctly reflecting a mixed craft profile, not an error. Clearing
                    4.5+ means a book scored strong across all six dimensions at once, not just that
                    people enjoyed reading it, so very few books reach that bar even among widely-loved
                    bestsellers.
                  </p>

                  <p className="methodology-disclaimer">
                    These are AI-generated distillations of aggregate reader sentiment, not human
                    editorial scores. They can miss nuance or be wrong — treat them as a starting
                    signal, not a guarantee.
                  </p>
                </>
              )}
            </div>
          </div>,
          document.body
        )}
    </>
  );
}
