export const SEED_BOOKS = [
  { title: 'Fourth Wing', author: 'Rebecca Yarros' },
  { title: 'A Court of Thorns and Roses', author: 'Sarah J. Maas' },
  { title: 'Iron Flame', author: 'Rebecca Yarros' },
  { title: 'A Court of Mist and Fury', author: 'Sarah J. Maas' },
  { title: 'A Court of Wings and Ruin', author: 'Sarah J. Maas' },
  { title: 'A Court of Silver Flames', author: 'Sarah J. Maas' },
  { title: 'Onyx Storm', author: 'Rebecca Yarros' },
  { title: 'Quicksilver', author: 'Callie Hart' },
  { title: 'The Serpent and the Wings of Night', author: 'Carissa Broadbent' },
  { title: 'Powerless', author: 'Lauren Roberts' },
  { title: 'Throne of Glass', author: 'Sarah J. Maas' },
  { title: 'From Blood and Ash', author: 'Jennifer L. Armentrout' },
  { title: 'House of Earth and Blood', author: 'Sarah J. Maas' },
  { title: 'Once Upon a Broken Heart', author: 'Stephanie Garber' },
  { title: 'One Dark Window', author: 'Rachel Gillig' },
  { title: 'The Cruel Prince', author: 'Holly Black' },
  { title: 'Divine Rivals', author: 'Rebecca Ross' },
  { title: 'When the Moon Hatched', author: 'Sarah A. Parker' },
  { title: 'Heartless Hunter', author: 'Kristen Ciccarelli' },
  { title: 'Crown of Midnight', author: 'Sarah J. Maas' },
  { title: 'Heir of Fire', author: 'Sarah J. Maas' },
  { title: 'Bride', author: 'Ali Hazelwood' },
  { title: 'House of Sky and Breath', author: 'Sarah J. Maas' },
  { title: 'The Ashes & the Star-Cursed King', author: 'Carissa Broadbent' },
  { title: 'Queen of Shadows', author: 'Sarah J. Maas' },
  { title: 'Reckless', author: 'Lauren Roberts' },
  { title: 'Empire of Storms', author: 'Sarah J. Maas' },
  { title: 'Spark of the Everflame', author: 'Penn Cole' },
  { title: 'Gild', author: 'Raven Kennedy' },
  { title: 'House of Flame and Shadow', author: 'Sarah J. Maas' },
  { title: 'The Book of Azrael', author: 'Amber V. Nicole' },
  { title: 'Phantasma', author: 'Kaylie Smith' },
  { title: 'Kingdom of Ash', author: 'Sarah J. Maas' },
  { title: 'Daughter of No Worlds', author: 'Carissa Broadbent' },
  { title: 'Tower of Dawn', author: 'Sarah J. Maas' },
  { title: 'Shield of Sparrows', author: 'Devney Perry' },
  { title: 'Caraval', author: 'Stephanie Garber' },
  { title: 'The Bridge Kingdom', author: 'Danielle L. Jensen' },
  { title: 'A Fate Inked in Blood', author: 'Danielle L. Jensen' },
  { title: 'The Knight and the Moth', author: 'Rachel Gillig' },
  { title: 'A Kingdom of Flesh and Fire', author: 'Jennifer L. Armentrout' },
  { title: 'The Ballad of Never After', author: 'Stephanie Garber' },
  { title: 'The Awakening', author: 'Caroline Peckham' },
  { title: "The Assassin's Blade", author: 'Sarah J. Maas' },
  { title: 'A Curse for True Love', author: 'Stephanie Garber' },
  { title: 'Assistant to the Villain', author: 'Hannah Nicole Maehrer' },
  { title: 'The Wicked King', author: 'Holly Black' },
  { title: 'Lightlark', author: 'Alex Aster' },
  { title: 'Two Twisted Crowns', author: 'Rachel Gillig' },
  { title: 'Flameborne: Chosen', author: 'Aimee Lynn' },
  { title: 'A Shadow in the Ember', author: 'Jennifer L. Armentrout' },
  { title: 'The Gilded Ones', author: 'Namina Forna' },
  { title: 'An Ember in the Ashes', author: 'Sabaa Tahir' },
  { title: 'The Queen of Nothing', author: 'Holly Black' },
  { title: 'A Little Hatred', author: 'Joe Abercrombie' },
  { title: 'The Name of the Wind', author: 'Patrick Rothfuss' },
  { title: 'Ninth House', author: 'Leigh Bardugo' },
  { title: 'Six of Crows', author: 'Leigh Bardugo' },
  { title: 'The Poppy War', author: 'R.F. Kuang' },
  { title: 'Babel', author: 'R.F. Kuang' },
  { title: 'The Atlas Six', author: 'Olivie Blake' },
  { title: 'A Memory Called Empire', author: 'Arkady Martine' },
  { title: 'The Priory of the Orange Tree', author: 'Samantha Shannon' },
  { title: 'The Bear and the Nightingale', author: 'Katherine Arden' },
  { title: 'Circe', author: 'Madeline Miller' },
  { title: 'The Song of Achilles', author: 'Madeline Miller' },
  { title: 'Mexican Gothic', author: 'Silvia Moreno-Garcia' },
  { title: 'These Hollow Vows', author: 'Lexi Ryan' },
  { title: 'The Midnight Library', author: 'Matt Haig' },
  { title: 'Vampire Academy', author: 'Richelle Mead' },
  { title: 'City of Bones', author: 'Cassandra Clare' },
  { title: 'An Enchantment of Ravens', author: 'Margaret Rogerson' },
  { title: 'Strange the Dreamer', author: 'Laini Taylor' },
  { title: 'Daughter of Smoke and Bone', author: 'Laini Taylor' },
  { title: 'The Night Circus', author: 'Erin Morgenstern' },
  { title: 'Nevernight', author: 'Jay Kristoff' },
  { title: 'Red Sister', author: 'Mark Lawrence' },
  { title: 'The Jasmine Throne', author: 'Tasha Suri' },
  { title: 'A Master of Djinn', author: 'P. Djèlí Clark' },
  { title: 'The House in the Cerulean Sea', author: 'TJ Klune' },
  { title: 'In Other Lands', author: 'Sarah Rees Brennan' },
  { title: 'The Goblin Emperor', author: 'Katherine Addison' },
  { title: 'Legendborn', author: 'Tracy Deonn' },
  { title: 'The Starless Sea', author: 'Erin Morgenstern' },
  { title: 'One More Bite Book One', author: 'Odette C. Bell' },
  { title: 'Kingdom of the Wicked', author: 'Kerri Maniscalco' },
  { title: 'A Dawn of Onyx', author: 'Kate Golden' },
  { title: 'The Dead and the Dark', author: 'Courtney Gould' },
  { title: 'The Shadows Between Us', author: 'Tricia Levenseller' },
  { title: 'Flame in the Mist', author: 'Renee Ahdieh' },
  { title: 'The Wrath and the Dawn', author: 'Renee Ahdieh' },
  { title: "An Assassin's Guide to Love and Treason", author: 'Virginia Boecker' },
  { title: 'The Girl the Sea Gave Back', author: 'Adrienne Young' },
  { title: 'Sky in the Deep', author: 'Adrienne Young' },
  { title: 'House of Salt and Sorrows', author: 'Erin A. Craig' },
  { title: 'A Study in Drowning', author: 'Ava Reid' },
  { title: 'Elektra', author: 'Jennifer Saint' },
  { title: 'Ariadne', author: 'Jennifer Saint' },
  { title: 'The Wolf and the Woodsman', author: 'Ava Reid' },

  // Batch 2 — catalog expansion, added 2026-08-07
  { title: 'Serpent & Dove', author: 'Shelby Mahurin' },
  { title: 'Blood Vow', author: 'Jennifer L. Armentrout' },
  { title: 'The Crown of Gilded Bones', author: 'Jennifer L. Armentrout' },
  { title: 'The War of Two Queens', author: 'Jennifer L. Armentrout' },
  { title: 'A Fire in the Flesh', author: 'Jennifer L. Armentrout' },
  { title: 'A Court of Frost and Starlight', author: 'Sarah J. Maas' },
  { title: 'Shadow and Bone', author: 'Leigh Bardugo' },
  { title: 'Crooked Kingdom', author: 'Leigh Bardugo' },
  { title: 'King of Scars', author: 'Leigh Bardugo' },
  { title: 'A Touch of Darkness', author: 'Scarlett St. Clair' },
  { title: 'A Touch of Ruin', author: 'Scarlett St. Clair' },
  { title: 'King of Battle and Blood', author: 'Scarlett St. Clair' },
  { title: 'Kingdom of the Cursed', author: 'Kerri Maniscalco' },
  { title: 'Kingdom of the Feared', author: 'Kerri Maniscalco' },
  { title: 'Neon Gods', author: 'Katee Robert' },
  { title: 'Electric Idol', author: 'Katee Robert' },
  { title: 'Wicked Beauty', author: 'Katee Robert' },
  { title: 'Radiant Sin', author: 'Katee Robert' },
  { title: 'The Iron King', author: 'Julie Kagawa' },
  { title: 'House of Hollow', author: 'Krystal Sutherland' },
  { title: 'A Deadly Education', author: 'Naomi Novik' },
  { title: 'The Last Graduate', author: 'Naomi Novik' },
  { title: 'Uprooted', author: 'Naomi Novik' },
  { title: 'Spinning Silver', author: 'Naomi Novik' },
  { title: 'Malice', author: 'Heather Walter' },
  { title: 'Misrule', author: 'Heather Walter' },
  { title: 'The Traitor Queen', author: 'Danielle L. Jensen' },
  { title: 'Ruthless Vows', author: 'Rebecca Ross' },
  { title: 'A River Enchanted', author: 'Rebecca Ross' },
  { title: 'A Fire Endless', author: 'Rebecca Ross' },
  { title: 'A Darker Shade of Magic', author: 'V.E. Schwab' },
  { title: 'The Invisible Life of Addie LaRue', author: 'V.E. Schwab' },
  { title: 'This Woven Kingdom', author: 'Tahereh Mafi' },
  { title: 'This Cursed Light', author: 'Emily Thiede' },
  { title: 'The Foxglove King', author: 'Hannah Whitten' },
  { title: 'The Hemlock Queen', author: 'Hannah Whitten' },
  { title: 'For the Wolf', author: 'Hannah Whitten' },
  { title: 'For the Throne', author: 'Hannah Whitten' },
  { title: 'The Hurricane Wars', author: 'Thea Guanzon' },
  { title: 'Bloodmarked', author: 'Tracy Deonn' },
  { title: 'Iron Widow', author: 'Xiran Jay Zhao' },
  { title: 'Sorcery of Thorns', author: 'Margaret Rogerson' },
  { title: 'Belladonna', author: 'Adalyn Grace' },
  { title: 'The Bone Shard Daughter', author: 'Andrea Stewart' },
  { title: 'A Deal with the Elf King', author: 'Elise Kova' },
  // Already existed in the DB (id 250) but had drifted out of this file at
  // some point, so it was silently excluded from every batch that loops
  // over SEED_BOOKS rather than the DB directly — re-added so it's tracked.
  { title: 'The Nightingale', author: 'Kristin Hannah' },
];
